version: '3.8'

services:
  nanolog:
    build: .
    container_name: nanolog
    ports:
      - "8080:8080"
    volumes:
      - ./data_docker:/root/data
    environment:
      - RETENTION=168h
    restart: unless-stopped
